language: node_js
node_js:
- '10'
before_install:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo $TRAVIS_COMMIT
- echo ${MESSAGE}
install:
- yarn
test: true
script:
- yarn docs:build
cache: yarn
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd dist
- cp index.html 404.html
- git init
- git add --all
- git commit -m "xxxx"
- git push -f "https://${GH_TOKEN}@github.com/rihuachen/rihuachen.github.io.git" master
env:
  global:
    secure: eoWvKhR/YUojHJz6BV460PkHAY/eB/T6rxexgtvI79lcavXAS5j21S5z0m3tCbsUZ9JXsw6p4OabOs4xSc3Ip/Bf3BJyrCRyFpimvn4Zys0WhIT3sGQDa5fx5Rx+Kg3Ab5i0uZsP0uo2QKVVGHEUKgCcad5kB1EehAMtspx1zfPe4Xii1UKgPXKxXuSIldtYJNGga03jQVYo9umUYbsF1hZxnnZYfH+RNvNs3OcnnuZECUEGh+QsXmncxSHW5TfsN1qp8Z+QwcXfWLaTktM18cwBRgaVsQIPcy1mwNqDi/dbMn7ZMbafQLVeItIGTqK27qa3uh1xfCoznaIzTnbgcvDw3oR+JRyhnkxglGxGqTzcnxW3IpdUi0IyoUOOUCl7wi9uGdetaYjPeFIxcYI9KYHormsvxDGz8dNBDQPwIzd6htlSV1ep7TZlBQYKRgx3O7bDloYcX96u7b2JHvnZ3eHLdtZ2+5Qu5FugOfBsBZMgk8ZW9gKMdERGsPxHWZZCDFaLnRri6k4D0ijD/dUUnpFApL27bTbt2GwxABoSUz3fuhF7A1KXV1M25YxIhCU+Xj8X9KW/gV39Rs/Mhy+tOwyVF/+8PhnaEtB7anYPVqRasX2REF2Ci6UQV8OY/L+dVXy3jDDihThXyobHW3P9MR75k8lGMO0c78qeFKnODxA=
