language: node_js
node_js:
  - '10'
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - echo $TRAVIS_COMMIT
  - echo ${MESSAGE}
install:
  - yarn
test: true
script:
  - yarn docs:build
cache: yarn
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - cd dist
  - cp index.html 404.html
  - git init
  - git remote add origin https://rihuachen:$GITHUB_TOKEN@github.com/rihuachen/rihuachen.github.io.git
  - git add --all
  - git commit -m "${MESSAGE}"
  - git push origin master -f
