language: node_js
node_js:
  - '10'
before_install:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - echo $TRAVIS_COMMIT
  - echo ${MESSAGE}
install:
  - yarn
test: true
script:
  - yarn docs:build
cache: yarn
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - cd dist
  - cp index.html 404.html
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: '$GH_TOKEN'
  on:
    branch: master
  repo: RihuaChen/RihuaChen.github.io
  target_branch: master
  local_dir: dist
env:
  global:
    secure: 'w6HGNPRnRnF81uTGsARQwALMbuu4kLOXVdhHwPI8ONWE/D0fUowLB+j5HYOvkul9yxslKCxVBSsXZ5GUAsE5UtraOzhrIDRAnKD/vUT3Mka/AIfntTnzdYuc5dinRuWp+/xHyWpeNukoTeyLYCWqN15uthyy6KMej8fZBmHa1i8cahyEygjilxUcQ5f+6dBMly488g+8UDhLoyQQS2G8eK/wT5uiOE9WuZZmK6YClyDH+JekYrvbM/T7DSDMYxcxxM0GwasypuJ9z2zuYsnPROfB12lQylwlKRxqlwX6ajW0E6+ociOODnINejbTChz+EgUEN2DW3v5T7vFabTfsANLRn8qXNLBvhRaNUwH+tGeHaAuM4kkgbCBddw2GjUAcOF6u25lQjqwuvr5k2DGtI/dt21MQ9hy2ZSfwzUaRcJiBpL9dybMgMwXfjhS0sF/EqE6kxonB7R+dVfDJFnVhC8RMD7Ht/TSjZ3D3iKh7/GsJAAzvUgEFVmBUvHgSHABwal5UlbkFXUK4tKM9Ayp9/gWb48Q1i0qh9rtrTKjh9WoMnvHgwpNlehkNUatEANU+fOmJLB3KbZ9tI3HtGNL1AnqhMdJRglOC1M8m6NGTjmia1FqPz4hfeMn0GDK3F0RAf2m7p35D9+v1iJt72rFPZBExPtAWwLOrIpU9l7ftPQI='
