language: node_js
node_js:
- '10'
before_install:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo $TRAVIS_COMMIT
- echo ${MESSAGE}
install:
- yarn
test: true
script:
- yarn docs:build
cache: yarn
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd dist
- cp index.html 404.html
- git init
- git add --all
- git commit -m "${MESSAGE}"
- git push -f "https://${GH_TOKEN}@github.com/rihuachen/rihuachen.github.io.git" master:gh-pages
env:
  global:
    secure: mWiR/4Z2lasMB4UHDjHk3av3/w17JX9Q0oyUPYWT8ckpMB7Bse4zbyrA62w1EQOzfe4aajMhc+qjyTD7ZJpqEomZgtjMRfd4K2NXLDJcwqw8xxgso19EsTvshEKco2My8h1EZeZwCbjyohW0X7a9t25/5qeygfVo3VEW4Be/qJSUP5nIOT+lEYd/Jif2aq1sBWLQRILvGQvbTINu4W3uzW9DFzYPtFyfzlWBAlbqgsRPYp8CQiMhXGZz/I2DDD47KRyTBnrISd6R/4MMjKJm1fLt9JsZhy331t6ryurMq3MH9CR29Bo4Yag7dTdoNYR1trqWQIiDNi3odwmi07PPd+tPjgiN932Ju/W2hOF2kpZUMh9aVRaOLuqVSKvyepCUBEDnK3DlKvohpq/UHHOpOweV083Gg5CKWmXYUDtNeencBoFTbQzDYAMO5eJipxPz3zg6s0pJeanI0oDa++I5F8Yb32KNVBDKQ7nt2nJTkLqTu8a3gxqDReGjfLi3LwjVSVkWvgFMT3Vk3wrlPJDf7251Vlx8oYICsepJjydOloaEQniGV/QbeORO7fGNr/X2OQ8RjWmZvWGl/tFb511hgoWeufmd2YyaCVfZ3cq8e9UTo0QnCm1PmEodr9cyVGBUKR2s1jEZcXdRgdhMmid+YbKAzca6nZdODKLa1ihBWoE=
