language: node_js
node_js:
- '10'
before_install:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo $TRAVIS_COMMIT
- echo ${MESSAGE}
install:
- yarn
test: true
script:
- yarn docs:build
cache: yarn
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd dist
- cp index.html 404.html
- sed -i "s/GH_TOKEN:$GH_TOKEN\,/''/g" umi.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  on:
    branch: master
  repo: RihuaChen/RihuaChen.github.io
  target_branch: master
  local_dir: dist
env:
  global:
    secure: RkSA5H3uta8rLJeZemOIGU0dj/BUorB8+mjx/jfhbnxtXbmiLW3IeUBozZqu7urvme8s9vaN0VE6ZKczUixvoX+lo+8AqgrqnwuxC6ckDweuPm/bv7re4JTaIgQhPEPzW5Of437nfraYTUhS8Cs5xLr7NRw8085hrnlrrAZdZt7B7/hq2qw3dlVhIabf0Yg3cZYXbSZ5TUJhdsGCmyP88XTQcTE3BxKfQ9AE46W0e8UCUjA9blei1EorWBsOwWX0FY3EHrrMffdm44cu5rxQI0kzFxlscUgAmijqI4DBKgAIqR9JI5yVbgj8VFNy2lHpkqiNnMbTYkh/IbSZcZERabTcpMwaY9A1lNvp+igkGYlpcwtAHj/JY5NhyHD7TwADDsOUdlwiei+uugYvzm8ZjCQH4e6ZoR+0DDv9M+oqBAUiYLsza0sCm/yC2YwRx2BtQt43zWmapua+2EVBfocGgrqURRpLPiMZ6bCqlUk/mNqVVJdiyJfzEyZp7tnmSG724A+CZ404LAMrXiaRtnlij1sYRjTwXoz64BGJe9axLVdm660B1+vZv+MHaDCJSRoWb4qyx18hMDUxGXaHooir6B9pv6dZAnfv6v5uoHN2XAja7XXRqGl8xba9AGv/uMEv05K2vNPP6NJ7m/P5n94YZtvU/92LMgIkLdtvJgcKKv4=
