language: node_js
node_js:
- '10'
before_install:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo $TRAVIS_COMMIT
- echo ${MESSAGE}
install:
- yarn
test: true
script:
- yarn docs:build
cache: yarn
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd dist
- cp index.html 404.html
- git init
- git remote add origin https://${GITHUB_TOKEN}@github.com/rihuachen/rihuachen.github.io.git
- git add --all
- git commit -m "${MESSAGE}"
- git push origin master -f
env:
  global:
  - secure: Hod8upNzS8JpmmXuryxE7toDX0b0wvRJaXyDVHTdhf/GEC/walT+YDgtAlP+InPOt4MoyyH6VklPcMGMcS/kML3wwb25usDmjtazchGztr5sN6iqqJMvR0tx+FdJF5KPneYmZW2w7gFE3onfvN/FLCwuDLTudlucpgLdgMdDHdK60F3CMZMvKOEvCtKqjud2ePyLFVe3p/gIoUImKQnQTcnELXJl/o1Yzumnj8KuKvLTDL66BCZMusJfTB2ZSc2vrsPg5VtjsWDLYd4cij6nQzFTN9aJE5hGNhmxb0NwL9wt3WLOTWJQGzIU4ELJowMFJWUNmi1J03bNmYBwgyGBeD0iiS5v42pRteJgD8h2i41YUw5ibEbWca4HGU8DE7vOlNm9ocnrvwgh7+COSoNDJ3IB/Kv4wDbn8FCGLk8SlUVjtIs0EmQ5XNEW7Y4brp36+5GbqD7ltoY7yTdRp1zVxUzHtg95iPYuVQ9dHqKqEt9KvvWAPXa7JIfHHajDN0aUBdgW71/xt8Rh833fJG2MQtp7Q3xhmG0+TmCh/nwE4M85T6R1kucJyo7qJl6GjevZiF9hanoD57LsjmcuB9120dZjTFeuAuJwCQUifKv03k99/lAc4Qiec2+WHdxXTT0n2d2reABfFyH2ak6DbLsxbr7nftItLjFYC2Yi0/xUvx0=
  - secure: ovGgUJydYX7PiwxJapCZioMqrkWrSgx15bFZbkLn7eaPRLxP12wQq/24b87pVoWpZXaq6kAJOkFf4Y6jIDw6O1R1wehK+fS9E+0o5vEgFWlTSPQIRDX72I7fGxft/yz03fRATIa3YXuLGxI0V7FPrKE63Gmg2tSIS2OMBNyjEgKoTwPuWOOfOW0eA2cTuSqW8gNEuNniuphJBft6jCMXw2tH+gtayiEUoY6N7k3Ctkk+N85yLtkY6CqkiUzulr+GmUtp3jW6Xfruytqpr0LSFhDn1JMEG6EovZSimuxJVZLzUXakI1I74LQmRbj3nmf76tR9zMFGfDikT/wQhpgzwwLzu4weep3ohQBT/t1z0AEuzz4XQbW1do2bWkuIfHeug5xEY6E4b01/f4wWAxNFZbImGff9OZBDFa8MenC/fgimD6BbNJY6WtPYLgYVJpO58L1p4GOIIMQ8aU6ht2ZHb4/8+Ed8NDsEZP17gjiVsxqtXqCqvy77ftKPW6n8hX/25sECueYha/i9sQ3zxbVt+5xCVQQP0WDxK6EfDj6RB/1wgrqu20EIXXXwknKWjWVnjZtl9ABfhQZK0Vgr0yrgSWFLe+fl4vkCDrCjvRA3sjzSL2yFWwVJ5Gr+u4AFg1WkWFeKGhOFqFte18j3Rv6d01062efM/LQBqGTDXmjC9FI=
