language: node_js
node_js:
- '10'
before_install:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo $TRAVIS_COMMIT
- echo ${MESSAGE}
install:
- yarn
test: true
script:
- yarn docs:build
cache: yarn
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd dist
- cp index.html 404.html
- sed -i 's/GH_TOKEN:$GH_TOKEN,/""/g' umi.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  on:
    branch: master
  repo: RihuaChen/RihuaChen.github.io
  target_branch: master
  local_dir: dist
env:
  global:
    secure: yhZZhHTjam5B+oYz8f/JyJOH9kB5VIt2Xoms/6EBz27CpZlGCCM4iw3hswzC+EQX8xY+X/yT18eFsszL8hol7VHwme90Mvil9epQhUPR4TLqZKET0ng4ZudLLgZkGeUn287eQ3dumMgC4E9qDdOlHmjf3Fx0LsymRXaX7vv4G1xrY+M5gXrFRwQjpC8Ia+FnswgsCevWJK6uXmKUYDPuiQXY/S20+vbMUmdgGGhaVaZQG5IOUiJUC0RL4MMgvDmaQYxd3NP64FOMOsLTViPgqaShTnk5obtEeoFCTjwXq1y4zdlFMAtsMDrD1zSn9pfsTxsYMhg02ZBOg/K/FiV9Xhnb5muCUnR1toLtQHeujRW/BT3VDPH25rlGDSzKaoOP8fQOFVmt1rSVeBTesF24onREB9JbtiHc5gWJtjdLNpj3+CPjXvSn/G0YOTwihEUwO+obdLt4p9ildgN9wvsqYKrAiSK1vOvph1GliomXvd6h7qcI3p0K1qewsA6hEZQXaPRyd54+JEFHrOIH1NjXIooagHiCSvfn4+D+MW1WfZp8UoghkIJUNn61vRJmi0gPYuI3xc9TEuBguA4gDmVjc+jXEdyje0JWHSqgAATJHgnatBlXnRlX6upXA9pmXradR50R36KWVCj5ReaoyoHUIQuSRzBg6b3xJCLxTs8/VV8=
