language: node_js
node_js:
- '10'
before_install:
- composer config --global github-oauth.github.com "$GITHUB_TOKEN"
install:
- yarn
test: true
script:
- yarn docs:build
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: pZuDWyqtbXiQY3RWT8YLKNvrS8eIyUnO6ctwMBZEYTt8YADvXIcU9AotjCHE8ydS/+q5YsUuD+RZMsHq31kWVnRH3HGGcKUP1wAXcsfV4dIbF3C5TnbPZAXhUxl1y9noml0+2OycZdFtoAxvBhKlLQG8paxBSg79IEwArJ3x37zCeMCAhV8bYrlAvz0b7LBpGRvp9L/qi1fIgOzu8aHt5zp2SCTfABeANU/nzkC8csoxCEtMacVyWa9tJQOMciIrTcDtRgRedXiObzFaqVJhIYdOw0E2mK1bJQ/03soB1lJW7vJKFwskRoupKC3koLtvscPXau+L40akOg/d4nfzCaoqp2DjLW4Nad94kKHbQ+9mbkIU80QXUBRtPMjNNm7yiH93bqdDpj0TQwWWXDkyI2cvCYztlS5ubTNTYe85Nghkv51HTwNYjQ1LaNoIyKSRYtTGbXlNAifuk2eYvvhjJ5YI1vBq06NME3tBaUONanH/j7GDLvUJNr/ZT+zWnApSCltnrtfgoferiYt749oVzWaocJepa9nYMeWze13LRYgYXx/azPZhUUzVjGLxtmEGM1SFF2siiXZcp6NmWk9IU/UpYpun8LlDl8pGFH7C3Ov2Vj0mDD6ciMLJ4vBaOFW+uq+/X8kbLAwtuAgq+gL5OVf821z2zaz25llz1Uq0WE0=
