language: node_js
node_js:
- '10'
before_install:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo $TRAVIS_COMMIT
- echo ${MESSAGE}
install:
- yarn
test: true
script:
- yarn docs:build
cache: yarn
# after_success:
# - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
# - cd dist
# - cp index.html 404.html
# - git init
# - git remote add origin https://rihuachen:${GITHUB_TOKEN}@github.com/rihuachen/rihuachen.github.io.git
# - git add --all
# - git commit -m "${MESSAGE}"
# - git push origin master -f
deploy:
  skip_cleanup: true # don't clean generated site
  github_token: $GITHUB_TOKEN # provide the encrypted token
  on:
    branch: master
  repo: RihuaChen/RihuaChen.github.io # optional, defaults to current repo
env:
  global:
  - secure: FlhASsBh4pucMIk5iKkg6K1LSWyb7zpQwf0o1QNgQJfen1leZAJApeprxzPFvcaGvxFO5uL3sZHUGVMhUmPL2Vxr021Xi2dhC2Kzd44qO6RJcsiPboCNhk44QWP9iGqqu10sucpHvYJztQUaZT8ZwiHp+FJzzr7eBlWsmgE/BTfLNSJUw0wPJdYPxN6LOCElikeVtxYE2SLNsUCpubAPuGRiRu8tfn4XtcuEevyRfRMPT+es3zRLGkvSODtdSPSUXoUT+RhkeDDULvqL5TjKdiSG4XUKOmxb2o4DGMB2pGCK0H4/jq+7Tb5O2H59Ag+ut+ZfuELY/21cz+wWfor6Y84dqkrYt8QU9DGzdm25eEk4y7T14fwyeasUmSmcb99LtgDo0U66IzemV1n/psMnzzzzzMcRk3oIIHBunkW5h/0NW2wSXdrGVkCoMQfpITLNC+PmyxyRkAdotJbpkpIAZnqLS5hOD0mhi5W9sPQxv7P0VdzTBDfMsPB5flfmjhxyDYyT9YFeR1gYZA4mGXt0b+NeZDhuWZBeGH9rDgrsi7KhK5KWrmt6EtwrehTNrvTVOKK63K0yjl90Uu6Ev7NLOKjOkGFyCiOVcCt9zPm2UWfVpHik/3szI5vcb1nyppkI1qifwM4Rma0U7uqd0GuRj8CVa8GZba5lwKpIeBA9+7E=
