language: node_js
node_js:
- '10'
before_install:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo $TRAVIS_COMMIT
- echo ${MESSAGE}
install:
- yarn
test: true
script:
- yarn docs:build
cache: yarn
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd dist
- cp index.html 404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  on:
    branch: master
  repo: RihuaChen/RihuaChen.github.io
  target_branch: master
  local_dir: dist
env:
  global:
  - secure: ccvGOnlz1SCc+f3buWbk9Wbf06ABW1qK5OUJa+bWWSdrzeUI5YlkBOQfyuQg8JIIxu0ljR4AcS1uv0mMxOuLa4TgsdBHu/jQjjiENKA54T4UkV5o+pjJQmZwZns4RsBXFP3JvMrQ2iWNmdOFdasjCnoqt2v8fKrNc3rmz9LH4o1LIHfO5xIGxndOdiZRlXQJwkDkgSGi7LCpFIIrP+YJ8h73D3I3/6s3OwWIVj4qjLY3ZYuKITNTorwDJ0B4QjLcyAplV+c4qsygIUH3W4tgK81WzRLPEpFFEz2msNMZsMQA/aKCzdUjsFdPN+d2mzROjDnrkxy9zIEMFBfb0TKpv43LNKzMvwsVnpssqwLNtqCvN0LQUw7mfErcASXo/KzUeiYPt/QesAlwqd1OXI29bnx1pbzKhTE4oTM6fyKQzkUrbl0v6fVf5Ohqgi7cvg84nDYjW3Gcyo+CyUYIh0Yf5FGSmhIPsQiJS8XO3TuMo6NzNNY4b9QmLW4pTUY5skwI4vQeo5Kf0RZUefqevFv/y/I3DJNJXmdx3OY8gyJ16Gtz/O1Nn2tcxtGNu5Sy18j6P+uOVlylMSPohTTUUFd3YaH+0GL+MNapR2RXWIWUCjIoVmcKKXdB0dhyChNqVzJRi+zi3Vp7ybF2TeS7hP53fwno+KsTHAakg4o32h9d4aA=
  - secure: E/E9rU4n/GhVg6dW9NzH5sN9uQR5NMFkz2YHnpWsBjHvNo50rLHpZMqGnMY9MVMHqOGdvYS9X+KLC9oAa4b1a3z2ETglsIikMnLTuJbMCiRAiHn9ECpo0JaArovn1tdaTwdIxX+tJ6WL6yFAMe7BjBdPPo30huhz7JLgtwupf6gpRvU7LmMfgggjOqh76qq+QgXxVTaQs8s6qq+u7vPPjcReHShOM1V7Mqakp5wnTr1aHQyCDh7yWBSOmId2CkXa1id2Io7Oseidxia5yEs30XwBPatMD1EXfFZP8e/OmsMIL8p+B6SfQOLBYm/zOkNBad/32FbfCC9vvmeE52ltXLbJViYkKihEkJRe+thmjWEOW95W0t5jA6b1H19WKnYEjKAg8AvOUrLrDOfWwBoEL0ewS5uTIQynQOfjH0D7CZXj9RU+1xD8Jq0pD1IglcPKN00Rl2R5GLDvJzNzmIQxjZt8NAQg5HKp+pjh4iWpAV+FEiB4zbgrnI7ZwkwWo1Z3Vq4kJ6SCLDO7OQ6E2oJ9fVZPDO5FQDVDBJawjkH66iqt4guCxU7eBgFeeOGRVav3rJclC0cTLN+E/F14QSmLYBZgf47QDwfvDZpV8VPN7fApNe62axfOePFNewrmos4Ppd8DRfJJHqMoVcya8yMj0z5yBJV3YYT8biwP5oaJ5lQ=
