language: node_js
node_js:
  - '10'
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
install:
  - yarn
test: true
script:
  - yarn docs:build
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - cd dist
  - git init
  - git remote add origin https://${rickychenrihua@foxmail.com}:${GITHUB_TOKEN}@github.com/rihuachen/rihuachen.github.io.git
  - git add .
  - git commit -m ${MESSAGE}
  - git push origin master -f
env:
  global:
    secure: tQdUp4DquJ1Uysnw8ofDWnAhWkHypa2XwWLw8SZPbSsihd6kMODk1EQ7cbvedLp6tzxw3G6TR0pgPmN5ECb0lxiddQDXt9FdgkVdC3IGQjOEFPcu5O2yIiCFTjmgVzEktGQyBI3Fq8TXFmb2UBL8HKO4qzQWJIzFESJhjqDfQ/YwwnRd0BEZmjRFhuKmEAEcb7gmQkuN1BTuv/0vCf2z7DNBmSwqNAt9F+xWCPhULlDuzOkbuHsOYR/4BA1xrGa95VgyQehYnPbVn5bet3CeE4Mp1U3/OdXOVbAj6xpcV1xmI2DATKqO23ahFZ4OSbfmbzz4q+e3+b9+Wdnbor1C6pbUV/hqAHvO6IDcwJSSuc4tI+69wzyZ5DYvle/XTZMCJR2TAniBQu62whlmTbnJUjiuG5wVpfsdYv4iwF2r45xvHY+TEwXlC8m/KddFjmf1+vEZJ4sqNd0qEBsLkJqeCsQjHO2gbgYS/7wp7j8E2e3ddWXT2bCup1ivO6MO23TCHssibzITuF/AfzIeiM0+/+zxZtqi0Lns0+lp8zgKMI1B8d897Hsktp4Jlt1WCPRKCAyInbdW/7aRoRWT4fxRwx59ieridFjIXOashhLRsg/cjN7W6f7MNPgdDDxa3ZpUhWmOfwAkS6LIu7a48+hFITtiGqYIssDiCiw1GQ3nji4=
